version: 2.1

executors:
  my-executor:
    docker:
      - image: fundor333/hugo
    working_directory: ~/repo
    environment:
      BRANCH: master
      TARGET_REPO: fundor333/fundor333.github.io.git
      HUGO_OUTPUT_FOLDER: public

jobs:
  hugo:
    executor: my-executor
    steps:
      - run: hugo


  github:
    executor: my-executor
    steps:
      - run: |
        if [ "${CIRCLE_BRANCH}" = "master" ]; then
          echo -e "Starting to deploy to Github Pages\n"
          apk add --update git
          apk add --update rsync
          cd ~/repo
          git config --global user.email "builds@circleci.com"
          git config --global user.name "CircleCI"

          git clone --quiet --branch=$CIRCLE_BRANCH https://${GH_TOKEN}@github.com/$TARGET_REPO built_website > /dev/null

          cd built_website
          echo "rsync built code with checked out code..."
          rsync -r --exclude=.git --delete ../$HUGO_OUTPUT_FOLDER/ ./

          echo "add files to git..."
          git add -f .
          echo "commit files to git repository..."
          if git commit -m "CircleCI build $CIRCLE_BUILD_NUM pushed to Github Pages" ; then
            echo "git push files with force..."
            git push -fq origin $BRANCH > /dev/null
            echo -e "Deploy completed\n"
          else
            echo "Content not changed, nothing to deploy"
          fi
        else
          echo "Not master branch, dry run only"
        fi

workflows:
  version: 2

  btd:
    jobs:
      - hugo
      - downstream:
          requires:
            - github
